### ISSUE TITLE
Random number generation - contract deploymet failed

### ISSUE THREAD

**Issue by nosuchip** [oraclize/ethereum-examples#4]
- Using your contract from there: https://github.com/oraclize/ethereum-examples/blob/master/solidity/random-datasource/randomExample.sol
- Downloaded and put aside `oraclizeAPI_0.4.sol` and fixed `import` statement.
- Running `truffle migrate --reset` and see:
```
alp@mobby ~/proj/OGmobi/tr $ truffle migrate --reset
Compiling ./contracts/GetRandom.sol...
Compiling ./contracts/oraclizeAPI_0.4.sol...
Compilation warnings encountered:
..........
Running migration: 2_deploy_contracts.js
  Replacing GetRandom...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37022:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:210096:36
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:208875:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:210748:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:211038:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:211193:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:211153:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
```

I tried to comment out different parts of code and finally got that error happens when line `oraclize_setProof(proofType_Ledger);` uncommented in code. Here is simples contract I tested:

```
pragma solidity ^0.4.11;

import "./oraclizeAPI_0.4.sol";

contract RandomExample is usingOraclize {

    event newRandomNumber(bytes);

    function RandomExample() {
        oraclize_setProof(proofType_Ledger); // sets the Ledger authenticity proof in the constructor
    }
}
```

**Comment by D-Nice** [comment]
Which network are you trying this on? The Random DS isn't currently supported outside of Mainnet, and Ropsten/Kovan.

**Comment by nosuchip** [comment]
@D-Nice you are right, missed point that tried to deploy contract to testrpc.
